### ISSUE TITLE
Service rcd file can't be used with the chkconfig utility

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/fiware-sth-comet#129]
When trying to add the STH as a service in RedHat, an error is risen: the service do not support chkconfig. The problem seems to be that the scripts are not LSB-compliant. Just add the sections as described, for example, [here](https://wiki.debian.org/LSBInitScripts). You can an example [here](https://github.com/telefonicaid/fiware-pep-steelskin/blob/master/rpm/SOURCES/etc/init.d/pepProxy). The license is also missing in the script file, BTW.

**Comment by gtorodelvalle** [comment]
Closing the issue once it has been solved... ;)
