### ISSUE TITLE
Date filters on raw access

### ISSUE THREAD

**Issue by Johan-Paz** [telefonicaid/fiware-sth-comet#170]
It could be really interesting to have a range of date filters on the raw mode of accesing data.

**Comment by gtorodelvalle** [comment]
Hi! I just noticed that the functionality is actually implemented but not well-documented. I'll send a PR in a sec. including better documentation ;) Thanks!

**Comment by gtorodelvalle** [comment]
Fixed in https://github.com/telefonicaid/IoT-STH/pull/174
