### ISSUE TITLE
STH release version for docker

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-sth-comet#195]
Currently docker configuration is linked to release/0.1.0.
https://github.com/telefonicaid/fiware-sth-comet/blob/develop/Dockerfile#L11
```
RUN git fetch && git checkout release/0.1.0 && npm install
```

This should be update to use the last version or just develop branch

**Comment by gtorodelvalle** [comment]
Already fixed... ;) Thanks for noticing! :)
