### ISSUE TITLE
"Warning: possible EventEmitter memory leak detected" when running tests

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/fiware-sth-comet#24]
Currently there is an issue (https://github.com/Automattic/mongoose/issues/2073) about a possible memory leak when using #connection.useDB() which makes the following warning to be shown during the tests: "(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit." Another issue in Node.js related to this issue can be located at https://github.com/joyent/node/issues/5108

There are also some StackOverflow questions about this issue at:
  - http://stackoverflow.com/questions/26018752/warning-when-connecting-to-mongodb-warning-possible-eventemitter-memory-leak
  - http://stackoverflow.com/questions/15581978/nodejs-how-to-debug-eventemitter-memory-leak-detected-11-listeners-added

**Comment by mrutid** [comment]
Now it is happening!

Mongoose see it as "nice to have" not critical. Posible solution may be to cache la connection objects avoiding over use of the .useDB (leaky) method.

**Comment by mrutid** [comment]
https://github.com/Automattic/mongoose/issues/2073

It seem that it is possible to access to the mongoose connection array, so we can reuse from there instead of use .useDB(). Anyway we are limited to 10 DB (10 Services en IoT Platform). Recomendation: Never ever use ORM. Try to remove mogoose dependency is it is possible.

**Comment by gtorodelvalle** [comment]
Closing the issue once the Mongoose package has been removed from the STH code and the logs mentioned in this issue have disappeared.
