### ISSUE TITLE
[STH] review alarm rules

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-sth-comet#29]
Ex:
```
time=2015-04-16T15:27:37.874Z | lvl=FATAL | corr=NA | trans=NA | op=OPER_STH_SERVER_LOG | msg=Attribute value not aggregatable, alarm_status=ALARM
```
It could be WARN instead of FATAL

**Comment by gtorodelvalle** [comment]
Hi @frbattid , @iariasleon , @vgarciag , I prepared this Google Sheet for the STH alarm management: https://docs.google.com/spreadsheets/d/1Z5XTkxDySo8PdloglmCLIDqrCj73BUpa3JAi-7p_fl4/edit#gid=0

It uses the same format as https://docs.google.com/spreadsheets/d/1hk3D0lqDuHN2HXhhw4TSk7QconTf10I6LAc1h7RCAEs/edit#gid=11

@vgarciag , do we have to do anything else apart from elaborating this sheet (with double "e" :) )? (I know, I know, @frbattid , I should not be joking but it goes beyond my control... :p )

**Comment by gtorodelvalle** [comment]
Closing the issue since the alarms mentioned in this issue are already been used in production... ;)
