### ISSUE TITLE
Docker image in the official Fiware DockerHub repo

### ISSUE THREAD

**Issue by drasko** [telefonicaid/fiware-sth-comet#328]
Hello,
please push tagged image here: https://hub.docker.com/u/fiware, because it is missing.

Many `docker-compose` integrations just pull the images from the official repo.

**Comment by gtorodelvalle** [comment]
As discussed with @jmcantera, before including the STH component in https://hub.docker.com/u/fiware, the following issues must be accomplished:
1. https://github.com/telefonicaid/fiware-sth-comet/issues/357
2. https://github.com/telefonicaid/fiware-sth-comet/issues/358
3. https://github.com/telefonicaid/fiware-sth-comet/issues/356

**Comment by gtorodelvalle** [comment]
STH tags images are now tagged in the Docker Hub: https://hub.docker.com/r/fiware/sth-comet/tags/ ;)
Thanks!
