### ISSUE TITLE
STH says that server has established http://localhost:9876, but netstat do not show any listning at this port number

### ISSUE THREAD

**Issue by 080165** [telefonicaid/fiware-sth-comet#413]

**Comment by gtorodelvalle** [comment]
Hi, would you be so kind to include your `config.js` contents in case you are not providing any configuration information via environment variables (if you are it would be great to have this concrete values) as well as the logs you are currently getting? :) Thanks!

**Comment by AlvaroVega** [comment]
Closing this issue due to lack of response about the issue.
