### ISSUE TITLE
Deal with "killer queries"

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-sth-comet#431]
Some query API operations (e.g. on long time windows with millions of samples) can be very resource-instenstive. That may block STH and make it unavailable for other paralell queries or even worse hang the componente completely.

Thus, it would be nice to have some mechanism to check this kind of "killer" queries and deal with them (e.g. killing them, responding with 500 Internal Error or something like that, but freeing STH for other users).

**Comment by mrutid** [comment]
Probably limiting max page size by config where hLimit<=lastN<=config.maxPageSize.

With this approach It could be related/solved along with other pagination issues:
https://github.com/telefonicaid/fiware-sth-comet/issues/428

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-sth-comet/pull/437
