### ISSUE TITLE
Content Disposition header encoding issue

### ISSUE THREAD

**Issue by Adeeb-khan** [telefonicaid/fiware-sth-comet#433]
The particular request which has following assumption was put into STH-Comet, then STH-Comet process was going down.
  1. attribute includes Japanese languages (maybe includes 2bytes or more character code, it also happen)
  2. parameter of query includes "filetype=csv"

Cause:
  Filename of Content-Disposition header is not encoded in response.
  So if filename is based on Japanese, error is occurred and process goes down.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-sth-comet/pull/434
