### ISSUE TITLE
Npm installation

### ISSUE THREAD

**Issue by Raffa87** [telefonicaid/fiware-sth-comet#446]
Hi!
I tried to install sth using npm, but after `npm install` I get:

> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/centos/fiware-sth-comet-master/npm-debug.log
> npm ERR! not ok code 0
> 
 
Can you please help me?
Thanks!

**Comment by fgalan** [comment]
Which node and npm version are you using?

```
node --version
npm --version
```

**Comment by Raffa87** [comment]
Thank you very much for your fast reply!
`node --version`
v0.10.46
'npm --version'
1.3.6

**Comment by fgalan** [comment]
Maybe the node version is old. Note that packages.json states https://github.com/telefonicaid/fiware-sth-comet/blob/master/package.json#L20:

```
"engines": {
    "node": ">=4.8.4"
},
```

**Comment by fgalan** [comment]
Btw, as reference this is my output for `npm install`:

```
$ npm install
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@1.0.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated constantinople@1.0.2: Please update to at least constantinople 3.1.1
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN grunt-gjslint@0.2.1 requires a peer of closure-linter-wrapper@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN fiware-sth-comet@2.3.0-next No license field.

added 514 packages from 898 contributors in 35.89s
[!] 108 vulnerabilities found [1349 packages audited]
    Severity: 39 Low | 59 Moderate | 9 High | 1 Critical
    Run `npm audit` for more detail
```

Using:

```
$ node --version
v6.12.3

$ npm --version
6.0.1
```

**Comment by Raffa87** [comment]
I have started from the "orion-psb-image-R5.4" in order to getting started with the context broker. 
Could I update the engine? 
As a more general question, do you have any reference where the whole path (from Context Broker to visualize hystorical data) is explained? I am getting lost in the FIWARE documentation
Thank you!

**Comment by Raffa87** [comment]
Solved by updating npm. 
Thank you!
