### ISSUE TITLE
Deprecated mongodb dependencies  

### ISSUE THREAD

**Issue by AlexMavromatis** [telefonicaid/fiware-sth-comet#449]
I get this error after running ./bin/sth

_the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object_

It runs and works properly, but does not create any mongodb database.

**Comment by sanchit31** [comment]
Hi Alex,

Databases in MongoDB are created only when when you insert some data in any collection of that database. So, it's absolutely fine that no database has been created.

**Comment by sanchit31** [comment]
Yes, if the contextBroker is running and sth-comet listening to it. The database will get created once you run an update query in your contextBroker and it notifies the change to sth comet.

Please check the following:
1) Is your subscription query correct?
2) Whether orion is running on multi-tenancy mode or not?
3) Whether sth-comet and context broker are able to access each other?

Can you share your subscription query, update query, sth and orion logs?
If you see this in sth logs - **time=2018-09-19T10:43:21.501Z | lvl=INFO | corr=n/a | trans=n/a | op=OPER_STH_SERVER_LOG | from=n/a | srv=n/a | subsrv=n/a | comp=STH | msg=Everything OK, 0 requests attended in the last 60s interval**, then it means that no data has been received by sth-comet yet.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-sth-comet/pull/456
