### ISSUE TITLE
Document the values for aggrPeriod

### ISSUE THREAD

**Issue by antont** [telefonicaid/fiware-sth-comet#470]
The documentation only says that aggrPeriod is a mandatory parameter but does not tell the possible values, in https://github.com/telefonicaid/fiware-sth-comet/blob/master/doc/manuals/aggregated-data-retrieval.md

Also for the date parameters it's not documented what the format is.

**Comment by fgalan** [comment]
Thanks for the feedback!

We are always open to pull request with typo fixing and documentation improvements :) Maybe you could do one to fix this issue, please? Thanks!

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-sth-comet/pull/490 solves the problem. Closing issue.

Please @antont have a look and tell us if you find something is pending (in which case we will reopen this isssue). Thanks!
