### ISSUE TITLE
[SHOULD] Repo description, topics and URL Link

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/fiware-sth-comet#482]
Please click the edit button at the head of the repo and amend the description link and topics as shown (or similar):

### Description:

> A component of the FIWARE ecosystem in charge of managing historical and aggregated time series context information

### Link

> https://fiware-sth-comet.rtfd.io

### Topics

`fiware`, `sth-comet`, `historical-data`

**Comment by fgalan** [comment]
Done!

Please have a look and close this issue if you find it ok.
