### ISSUE TITLE
[MUST] Show versioned documentation

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/fiware-sth-comet#487]
On the STH-Comet ReadtheDocs project, all versions after 2.1 are not displayed

1. Goto https://readthedocs.org/projects/fiware-sth-comet/versions/
2. Ensure that **active** checkmark is ticked against relevant release tags

**Comment by fgalan** [comment]
Three last versions (2.5.0, 2.4.0, 2.3.0) has been added. Please have a look and close the issue if you find it now solved. Thanks!
