### ISSUE TITLE
Cors Request

### ISSUE THREAD

**Issue by caiothomas** [telefonicaid/fiware-sth-comet#500]
Is it possible to enable CORS using Docker compose?
Best Regards

**Comment by fgalan** [comment]
Could you be more specific please? Thanks!

**Comment by Siedlerchr** [comment]
I am facing the same isuse and I think the question is simply, is it possible to add a startup parameter to enable/set the CORS header? Simliar to how it's done in orion https://fiware-orion.readthedocs.io/en/master/user/cors/index.html 

Cause when I try to access sth-comet running in docker from a js application, I will get the usual error message 'Access-Control-Allow-Origin` header missing.

**Comment by fgalan** [comment]
I agree it could be a good idea to include such functionality as one (or several) configuration parameters (in config.js). We would be more than happy to review contribution pull request about it and provide feedback! :) 

The issue has been labeled as "help wanted".

**Comment by caiothomas** [comment]
in the file https://github.com/telefonicaid/fiware-sth-comet/blob/master/lib/server/sthServer.js you can add

```
 server.connection({
        host: host,
        port: port,
	routes: { cors: { origin: ['*'] } }
    });
```
Create var corsHeaders

```
    var corsHeaders = {
      origin: ["*"],
      headers: ["Access-Control-Allow-Origin","Access-Control-Allow-Headers", "Access-Control-    Request-Headers:","Origin, Referer, User-Agent"],
      additionalHeaders: ['fiware-servicepath', 'fiware-service'],
      credentials: true
    };
```
And in route server add corsHeaders in config.

```
    server.route([
        {
            method: 'GET',
            path: '/STH/v1/contextEntities/type/{entityType}/id/{entityId}/attributes/{attrName}',
            handler: sthGetDataHandler,
            config:{
		cors: corsHeaders,
```

It will enable CORS. Using docker-compose you create a "sth" folder and add the code with this modification using volumes. Tested in release / 2.5.0

```
  sth-comet:
    image: fiware / sth-comet: 2.5.0
    hostname: sth-comet
    container_name: fiware-sth-comet
    volumes:
     - ./sth/sthServer.js:/opt/sth/lib/server/sthServer.js
```

**Comment by fgalan** [comment]
Thanks @caiothomas! 

That information will be very useful to implement CORS support in STH :)
