### ISSUE TITLE
error retrieving using filetype=csv

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-sth-comet#513]
$ curl --insecure -i -X GET 'https://localhost/sth/v1/contextEntities/type/thing/id/thing:disp33/attributes/color?dateFrom=2019-08-04T22:00:00.000Z&dateTo=2019-08-07T22:00:00.000Z&filetype=csv' -H 'X-Auth-Token: 8aafca2d7fd7460e82db05a91db64681' -H 'Fiware-Service: smartcity' -H 'Fiware-ServicePath: /'
HTTP/2 500 

logs:

iot-sth                     | TypeError: reply.file is not a function
iot-sth                     |     at /opt/sth/lib/server/handlers/sthGetDataHandler.js:130:50
iot-sth                     |     at emitNone (events.js:111:20)
iot-sth                     |     at WriteStream.emit (events.js:208:7)
iot-sth                     |     at finishMaybe (_stream_writable.js:613:14)
iot-sth                     |     at afterWrite (_stream_writable.js:464:3)
iot-sth                     |     at onwrite (_stream_writable.js:454:7)
iot-sth                     |     at fs.js:2239:5
iot-sth                     |     at FSReqWrap.wrapper [as oncomplete] (fs.js:2205:5)
iot-sth                     | time=2019-08-06T10:23:05.554Z | lvl=ERROR | corr=n/a | trans=n/a | op=OPER_STH_SHUTDOWN | from=n/a | srv=n/a | subsrv=n/a | comp=STH | msg=TypeError: reply.file is not a function
iot-sth                     | time=2019-08-06T10:23:05.555Z | lvl=INFO | corr=n/a | trans=n/a | op=OPER_STH_SERVER_STOP | from=n/a | srv=n/a | subsrv=n/a | comp=STH | msg=Stopping the STH server...

**Comment by AlvaroVega** [comment]
reply.file is not a function" since hapi was updated. 
This method should be reimplemented.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-sth-comet/pull/520
