### ISSUE TITLE
non enough permissions over temp directory

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-sth-comet#514]
iot-sth                     | Error: EACCES: permission denied, open '/opt/sth/temp/color-1565085983660.csv'
iot-sth                     | time=2019-08-06T10:06:23.665Z | lvl=ERROR | corr=n/a | trans=n/a | op=OPER_STH_SHUTDOWN | from=n/a | srv=n/a | subsrv=n/a | comp=STH | msg=Error: EACCES: permission denied, open '/opt/sth/temp/color-1565085983660.csv'
iot-sth                     | time=2019-08-06T10:06:23.665Z | lvl=INFO | corr=n/a | trans=n/a | op=OPER_STH_SERVER_STOP | from=n/a | srv=n/a | subsrv=n/a | comp=STH | msg=Stopping the STH server...

**Comment by fgalan** [comment]
Fixed by PR #514
