### ISSUE TITLE
Incorrect Response format when filetype=csv is used with hLimit and hOffset

### ISSUE THREAD

**Issue by Madhu-NEC** [telefonicaid/fiware-sth-comet#539]
When **filetype=csv** parameter is used in combination with **hLimit and hOffset**, API returns response in json format not in csv format. 
Ideally, the response of API should be in csv format if filetype=csv is used.
For instance,
(http://localhost:8666/STH/v1/contextEntities/type/Room/id/Room1/attributes/temperature?hLimit=10&hOffset=0&filetype=csv) API returns response in JSON format.

**Comment by fgalan** [comment]
I looks like a new bug in the filetype=csv functionality, similar to the one you discovered in https://github.com/telefonicaid/fiware-sth-comet/issues/532. Maybe you could have a look and propose a fix in a PR, as you did with that issue?

Thanks!

**Comment by Madhu-NEC** [comment]
Hi @fgalan,
As per my investigation, there is typo error for filetype in case of hLimit and hOffset. At this [line](https://github.com/telefonicaid/fiware-sth-comet/blob/master/lib/database/sthDatabase.js#L494), filetype is mentioned as "cvs" but it should be "csv".
I have raised the [PR](https://github.com/telefonicaid/fiware-sth-comet/pull/540) for the same.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-sth-comet/pull/540. Thanks!
