### ISSUE TITLE
SemVer Docker images missing

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/fiware-sth-comet#549]
Since the `Dockerfile` was moved from root ( https://github.com/telefonicaid/fiware-sth-comet/commit/3690b62ac01679abb7444a659d153b8448b3c203 ), the STH-Comet automated build has failed:

Someone with appropriate access rights need to alter the config here:

https://hub.docker.com/repository/docker/fiware/sth-comet/builds/edit

![sth-comet](https://user-images.githubusercontent.com/3439249/96478035-7deb3580-1237-11eb-8d47-4895b3739bda.png)

In both build cases the Dockerfile location is now `/docker`.  Build **2.8.0** will need to be rebuilt or pushed manually.

**Comment by fgalan** [comment]
It seems I can edit "Dockerfile location" to `/docker` in https://hub.docker.com/repository/docker/fiware/sth-comet/builds/edit then click "Save" and everything seems to be ok (no error is reported by dockerhub web GUI and `/docker` stills there). However, if then I go to "Builds" (https://hub.docker.com/repository/docker/fiware/sth-comet/builds) then "Configured automated builds" again (https://hub.docker.com/repository/docker/fiware/sth-comet/builds/edit) the settings shows back `/`.

This pretty weird... maybe I don't have the right level of permision but dockerhub web GUI is failing in showming me a proper error when I try the modification?

**Comment by fgalan** [comment]
Having a look with the browser debug, whenever I click on "Save" I get

![imagen](https://user-images.githubusercontent.com/1534240/96496283-556c3700-1249-11eb-9814-9d375815606c.png)

Maybe this is somekind of temporal dockerhub-gitbub communication glitch? Don't know how to solve this :)

**Comment by AlvaroVega** [comment]
IMHO builds at https://hub.docker.com/repository/docker/telefonicaiot/fiware-sth-comet/builds are working fine. In that hub "Docker location" is "/docker".
What hub is in trouble @jason-fox ?

**Comment by AlvaroVega** [comment]
Moreover, other components (like iotagents) are using the same "Docker location" in "/docker"

**Comment by jason-fox** [comment]
`r/fiware/sth-comet` DockerHub will not update to use the `telefonicaid/fiware-sth-comet` GitHub repository. I have manually pushed the fiware clone as follows:


```bash
#!/bin/bash
findRelease () {
	docker pull $1:$3 
	docker tag $1:$3 $2:$3
	docker tag $1:$3 $2:latest
	docker push $2:$3
	docker push $2:latest
	docker rmi $2:latest
	docker rmi $2:$3
	docker rmi $1:$3
	echo ""
}

findRelease telefonicaiot/fiware-sth-comet fiware/sth-comet 2.8.0
```

Maybe this is the way forward - maybe we should stop shadowing and auto-building the Telefonica builds and just push releases to FIWARE?

**Comment by fgalan** [comment]
> `r/fiware/sth-comet` DockerHub will not update to use the `telefonicaid/fiware-sth-comet` GitHub repository

I have a doubt regarding this... Is it actually a problem with permissions? Or it is a bug in Dockerhub GUI?

**Comment by AlvaroVega** [comment]
If I'm not wrong r/fiware/sth-comet could be configured to use  "Docker location" in "/docker" and then build properly sth images. Is there any permissions problem over  r/fiware/sth-comet ?

**Comment by jason-fox** [comment]
> If I'm not wrong r/fiware/sth-comet could be configured to use "Docker location" in "/docker" and then build properly sth images. Is there any permissions problem over r/fiware/sth-comet ?

There is nothing wrong with that *in principle*, it is just that it doesn't work 😢  - the update to `/docker` doesn't stick. _I've tried_ . Whether this is a permissions issue or a DockerHub GUI issue or what I don't know. The upshot is that the FIWARE organization on DockerHub is currently unable to use the webhook coming from the Telefonica GitHub Source.

**Comment by fgalan** [comment]
> Whether this is a permissions issue or a DockerHub GUI issue or what I don't know

Maybe a support ticket should be opened in DockerHub about this?

It seems that the FIWARE organization in Dockerhub is working fine for other respositories. For instance, the Orion 2.5.0 version released today, as seen at https://hub.docker.com/r/fiware/orion/tags

**Comment by jason-fox** [comment]
I've fixed this by building off the FIWARE-GEs mirror image which tracks the upstream Telefonica image.
