### ISSUE TITLE
Missleading trace information

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/fiware-sth-comet#556]
At 
https://github.com/telefonicaid/fiware-sth-comet/blob/97206d060eed5c5b929d94963931582222e34332/lib/server/handlers/sthGetDataHandler.js#L60

In case of error accessing at a collection (raw or saggregated) the log message prints the Collection itself (null or [Object Object]). It should print the collection name (host, bd....) which is trying to access instead.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-sth-comet/pull/557
