### ISSUE TITLE
migrate mongo driver from 2.2.X to 3.6.Y

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-sth-comet#567]
mongo driver 2.2.35 currently used by sth is deprecated

But not only upgrade dependency is enought:
https://github.com/telefonicaid/fiware-sth-comet/pull/548

According with https://mongodb.github.io/node-mongodb-native/3.1/upgrade-migration/main/
main change is MongoClient.connect now returns a Client instead of a DB

**Comment by fgalan** [comment]
PR #568
