### ISSUE TITLE
Return 500 when DB is not connected

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-sth-comet#570]
(Comes from issue https://github.com/telefonicaid/fiware-sth-comet/issues/559)

If database is not connected and any API will be requested then it will return "500 internal server error" and in logs it will display "database is not connected".

CC: @SwatiNEC

**Comment by fgalan** [comment]
According to https://github.com/telefonicaid/fiware-sth-comet/issues/559#issuecomment-994287074, PR #560 addresses this issue.

@SwatiNEC could you merge master into PR #560 branch (solving any possible merging conflict during the process) so we can see how it looks like, please?

**Comment by Gauravp-NEC** [comment]
@fgalan , I have tried to re-base master branch with the PR https://github.com/telefonicaid/fiware-sth-comet/pull/560 in my environment but it did not solve the issue. There is no handling of error after the reconnectTries value is exhaust.

**Comment by AlvaroVega** [comment]
Fixed in https://github.com/telefonicaid/fiware-sth-comet/pull/572

**Comment by fgalan** [comment]
> Fixed in #572

Just to clarify, what has been fixed in PR #572 is to reduce reconnectionTries to a smaller value (30) with an inter-reconnection time of 1 second (instead of 5 seconds).

Thus I understand you can not resync PR #560 with master and address this issue. Tell us if you need something else, please.

**Comment by Gauravp-NEC** [comment]
@AlvaroVega @fgalan , I have checked the PR https://github.com/telefonicaid/fiware-sth-comet/pull/572. There is no error handling message in the PR when MongoDB is not connected and any API will be requested.

**Comment by fgalan** [comment]
> @AlvaroVega @fgalan , I have checked the PR #572. There is no error handling message in the PR when MongoDB is not connected and any API will be requested.

As far as I understand, the error handling functionality to return 500 when DB is not connection is part of @SwatiNEC's PR #560 (see https://github.com/telefonicaid/fiware-sth-comet/issues/559#issuecomment-994287074)

Is my understanding not correct? Could you clarify what PR #560 is really doing?

**Comment by Gauravp-NEC** [comment]
> As far as I understand, the error handling functionality to return 500 when DB is not connection is part of @SwatiNEC's PR #560 (see [#559 (comment)](https://github.com/telefonicaid/fiware-sth-comet/issues/559#issuecomment-994287074))
> 
> Is my understanding not correct? Could you clarify what PR #560 is really doing?

@fgalan,Your understanding is correct. The error handling functionality to return 500 when DB is not connection is part of PR https://github.com/telefonicaid/fiware-sth-comet/pull/560, but now the PR does not sync with the master branch.

**Comment by Gauravp-NEC** [comment]
@fgalan , I am looking forward to implement the error handling functionality to return 500 when DB is not connected.

**Comment by fgalan** [comment]
> ...but now the PR does not sync with the master branch.

I understand you mean that there are merging conflicts when trying to merge master into PR branch. This is usual business with git and the solution is to solve these conflicts. You can even to do using github, using the "Resolve conflict" button in the PR:

![imagen](https://user-images.githubusercontent.com/1534240/147214876-a76ff3b3-9232-4303-945b-192a6c223f1c.png)

**Comment by fgalan** [comment]
> @fgalan , I am looking forward to implement the error handling functionality to return 500 when DB is not connected.

Great! Thanks!

I understand you would coordinate with @SwatiNEC's (the author of PR #560)

**Comment by Gauravp-NEC** [comment]
@fgalan , I have raised the PR: https://github.com/telefonicaid/fiware-sth-comet/pull/574 to fix this issue.

**Comment by Chandradeep-NEC** [comment]
@fgalan @mapedraza 
Thanks for your work on this issue. 
Now we are verifying issue #559  and #570 with updated code of PR #583 in our environment.

**Comment by Gauravp-NEC** [comment]
@fgalan @mapedraza , We have tested the updated code of PR https://github.com/telefonicaid/fiware-sth-comet/pull/583 in our environment. Few  test scenarios are working fine but one test scenario is not working as per our expected.


1. Make sure that STH server and MongoDB are running and connected together.
2. Stop the MongoDB Container.
3. Start the MongoDB container when the` reconnectTries` value is exhausted.
4. Execute the GET API.

**Our expected test result :**
1. MongoDB should connect to STH server.
2. GET API should respond with attribute values.

**Actual test result :**  
1. MongoDB is not connected to STH server.
2. GET API respond with:
> statusCode: 500
> error: Internal Sever Error
> message: MongoDB is not connected

The expected result was successfully working in the PR https://github.com/telefonicaid/fiware-sth-comet/pull/574 due to the
`client.connect()` function in else condition.
   
 ```
if (isConnectionAlive()) {
        fetchCollection(databaseName, isAggregated, shouldTruncate, shouldCreate, collectionName, callback);
    } else {
        client.connect(function(err) {
            if(err) {
                return callback(err,null);
            }
        });
    }
}
```

**Comment by fgalan** [comment]
> @fgalan @mapedraza , We have tested the updated code of PR #583 in our environment. Few test scenarios are working fine but one test scenario is not working as per our expected.
> 
>     1. Make sure that STH server and MongoDB are running and connected together.
> 
>     2. Stop the MongoDB Container.
> 
>     3. Start the MongoDB container when the` reconnectTries` value is exhausted.
> 
>     4. Execute the GET API.
> 
> 
> **Our expected test result :**
> 
>     1. MongoDB should connect to STH server.
> 
>     2. GET API should respond with attribute values.
> 
> 
> **Actual test result :**
> 
>     1. MongoDB is not connected to STH server.
> 
>     2. GET API respond with:
> 
> 
> > statusCode: 500
> > error: Internal Sever Error
> > message: MongoDB is not connected
> 
> The expected result was successfully working in the PR #574 due to the `client.connect()` function in else condition.
> 
> ```
> if (isConnectionAlive()) {
>        fetchCollection(databaseName, isAggregated, shouldTruncate, shouldCreate, collectionName, callback);
>    } else {
>        client.connect(function(err) {
>            if(err) {
>                return callback(err,null);
>            }
>        });
>    }
> }
> ```

Please open a new issue with this topic, so we can discuss in detail (the current issue has been "exhausted" in 2.9.0 and it is now closed).
