### ISSUE TITLE
Use Telefonica's checkstyle file

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-sth-comet#8]
At least for Java developments, Telefónica has a `telefonica_checkstyle.xml` file that can be configured in your favourite IDE in order to check if the required style is being met.

I don't know if something similar exists for Javascript, I suppose so...

**Comment by gtorodelvalle** [comment]
I'll check it with Javier Martínez Álvarez ;) Thanks!

**Comment by gtorodelvalle** [comment]
I'll include the configuration files for JSLint included in https://pdihub.hi.inet/TDAF/tdigital-node-boilerplate as soon as my PDIHub account is reactivated ;)

**Comment by gtorodelvalle** [comment]
Closing the issue since it is already solved once the code of the STH has been made compatible with TID's guidelines for Node applications... ;)
